# =============================================================
# LAB 6 — docker-compose.yml
# Stack completo: backend FastAPI + frontend Gradio
# =============================================================

version: "3.9" 
  
services: 
  
  backend: 
    build: ./backend-iris 
    container_name: iris-backend 
    ports: 
      - "8000:8000" 
    environment: 
      - HF_TOKEN=${HF_TOKEN}   # token de HF pasado desde el host 
    restart: unless-stopped 
  
  frontend: 
    build: ./frontend-iris 
    container_name: iris-frontend 
    ports: 
      - "7860:7860" 
    environment: 
      # En la red interna el backend se llama 'backend', no 'localhost' 
      - BACKEND_URL=http://backend:8000 
    depends_on:
      backend:
       condition: service_healthy
    restart: unless-stopped 